language: node_js
node_js:
  - 10
before_script:
  - yarn global add netlify-cli
  - yarn add --dev https://github.com/ebidel/lighthouse-ci
script:
  - yarn build
  - LH_URL=$(netlify deploy | grep 'Live Draft' | sed -e 's|Live Draft URL:||')
after_success:
  - yarn lh $LH_URL
